-- 查询所有引用sk_categories表的外键约束
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE 
    REFERENCED_TABLE_NAME = 'sk_categories' AND
    TABLE_SCHEMA = 'semiconductor_db';

-- 如果上面的查询没有结果，尝试查询所有外键约束，看看是否有引用sk_categories的
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE 
    TABLE_SCHEMA = 'semiconductor_db' AND
    REFERENCED_TABLE_NAME IS NOT NULL;
